# Generated by Django 5.0.3 on 2024-03-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_remove_authtokens_date"),
        ("services", "0004_alter_activerides_time_completed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deduction_or_addition", models.TextField(max_length=255)),
                ("amount", models.FloatField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.users"
                    ),
                ),
            ],
        ),
    ]
