# Generated by Django 5.0.3 on 2024-03-27 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_alter_authtokens_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authtokens",
            name="date",
        ),
    ]
