# Generated by Django 5.0.3 on 2024-03-24 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authtokens",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
