# Generated by Django 5.0.3 on 2024-03-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0017_remove_authtokens_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveRides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_text", models.TextField(max_length=255)),
                ("requester_rating", models.FloatField(default=0)),
                ("responder_rating", models.FloatField(default=0)),
                ("feedback_to_driver", models.TextField(max_length=255)),
                ("feedback_to_requester", models.TextField(max_length=255)),
                ("transaction_amount", models.FloatField(default=0)),
                ("service_type", models.TextField(max_length=255)),
                ("scheduled_service", models.BooleanField(default=False)),
                ("time_started", models.DateTimeField()),
                ("time_requested", models.DateTimeField()),
                ("time_accepted", models.DateTimeField()),
                ("time_pickup", models.DateTimeField()),
                ("time_completed", models.DateTimeField()),
                ("time_finalised", models.DateTimeField()),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("pickup_place_name", models.CharField(max_length=255)),
                ("end_latitude", models.FloatField()),
                ("end_longitude", models.FloatField()),
                ("end_place_name", models.CharField(max_length=255)),
                ("distance", models.FloatField()),
                ("duration", models.FloatField()),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_rides_as_requester",
                        to="accounts.users",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_rides_as_responder",
                        to="accounts.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_started", models.DateTimeField()),
                ("transaction_amount", models.FloatField(default=0)),
                ("service_type", models.TextField(max_length=255)),
                ("scheduled_service", models.BooleanField(default=False)),
                ("time_requested", models.DateTimeField()),
                ("requester_text", models.TextField(max_length=255, null=True)),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("pickup_place_name", models.CharField(max_length=255)),
                ("end_latitude", models.FloatField()),
                ("end_longitude", models.FloatField()),
                ("end_place_name", models.CharField(max_length=255)),
                ("distance", models.FloatField()),
                ("duration", models.FloatField()),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_requests_as_requester",
                        to="accounts.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_text", models.TextField(max_length=255, null=True)),
                ("requester_rating", models.FloatField(null=True)),
                ("responder_rating", models.FloatField(null=True)),
                ("feedback_to_driver", models.TextField(max_length=255, null=True)),
                ("feedback_to_requester", models.TextField(max_length=255, null=True)),
                ("transaction_amount", models.FloatField(default=0)),
                ("service_type", models.TextField(max_length=255)),
                ("scheduled_service", models.BooleanField(default=False)),
                ("time_started", models.DateTimeField()),
                ("time_requested", models.DateTimeField()),
                ("time_accepted", models.DateTimeField()),
                ("time_pickup", models.DateTimeField()),
                ("time_completed", models.DateTimeField()),
                ("time_finalised", models.DateTimeField()),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("pickup_place_name", models.CharField(max_length=255)),
                ("end_latitude", models.FloatField()),
                ("end_longitude", models.FloatField()),
                ("end_place_name", models.CharField(max_length=255)),
                ("distance", models.FloatField()),
                ("duration", models.FloatField()),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_histories_as_requester",
                        to="accounts.users",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_histories_as_responder",
                        to="accounts.users",
                    ),
                ),
            ],
        ),
    ]
