# Generated by Django 5.0.3 on 2024-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_remove_activerides_time_finalised_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activerides",
            name="end_place_name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="activerides",
            name="pickup_place_name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="currentrequest",
            name="end_place_name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="currentrequest",
            name="pickup_place_name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="servicehistory",
            name="end_place_name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="servicehistory",
            name="pickup_place_name",
            field=models.TextField(max_length=255),
        ),
    ]
