# Generated by Django 5.0.3 on 2024-04-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0011_alter_activerides_end_place_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activerides",
            name="driver_latitude",
            field=models.FloatField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activerides",
            name="driver_longitude",
            field=models.FloatField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicehistory",
            name="driver_latitude",
            field=models.FloatField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicehistory",
            name="driver_longitude",
            field=models.FloatField(default=999),
            preserve_default=False,
        ),
    ]
