# Generated by Django 5.0.3 on 2024-03-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_currentrequest_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activerides",
            name="time_completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="activerides",
            name="time_finalised",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="activerides",
            name="time_pickup",
            field=models.DateTimeField(null=True),
        ),
    ]
