# Generated by Django 5.0.3 on 2024-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_alter_activerides_requester_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activerides",
            name="requester_rating",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="activerides",
            name="responder_rating",
            field=models.FloatField(default=None, null=True),
        ),
    ]
