# Generated by Django 5.0.3 on 2024-03-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0009_alter_wallethistory_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activerides",
            name="time_finalised",
        ),
        migrations.RemoveField(
            model_name="servicehistory",
            name="time_finalised",
        ),
        migrations.AlterField(
            model_name="activerides",
            name="feedback_to_driver",
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activerides",
            name="feedback_to_requester",
            field=models.TextField(default=None, max_length=255, null=True),
        ),
    ]
