# Generated by Django 5.0.4 on 2024-04-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0013_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentrequest",
            name="user_rating",
            field=models.FloatField(default=0),
        ),
    ]
