# Generated by Django 5.0.3 on 2024-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0008_alter_activerides_requester_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallethistory",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
