# Generated by Django 5.0.2 on 2024-04-09 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_activerides_driver_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=255)),
                ('time', models.DateTimeField()),
                ('is_requester', models.BooleanField()),
                ('active_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.activerides')),
            ],
        ),
    ]
